### ISSUE TITLE
Questions about the final result file

### ISSUE THREAD

**Issue by Song-10-YF** [qjiangzhao/TEtrimmer#25]
Dear Dr. Zhao,

Thank you very much for developing the software for automatic correction of TE annotations. I am also applying this process to correct my TE annotations. Does this software still correct at the level of consensus sequences? I would like to know how to obtain the final TE annotation file.

Looking forward to your reply.

Yan-Feng Song

**Comment by qjiangzhao** [comment]
Dear Yan-Feng:

Thanks you are interested in TEtrimmer.

By default, TEtrimmer won't do the whole genome TE annotation. But You can add "--genome_anno" option to enable that.

Yours sincerely 
Jiangzhao

**Comment by Song-10-YF** [comment]
Thanks! I'll try！

**Comment by qjiangzhao** [comment]
Yes. You can!

**Comment by Song-10-YF** [comment]
I tried using this command to re-analyze tasks that had already ended. The task quickly showed as completed, but it did not output an annotation file.

**Comment by qjiangzhao** [comment]
oh! I will write this to my list and fix this for the next version.
 
Anyway, TEtrimmer used RepeatMasker for the whole genome TE annotation. You can use:
'''
RepeatMasker <path to/genome_file> -lib <path to/TEtrimmer_consensus_merged.fasta> -pa <your_threads_num> -dir <output_dir> -s -gff -xm -a
'''
for the TE annotation.

**Comment by Song-10-YF** [comment]
OK, thank you very much!

**Comment by qjiangzhao** [comment]
no worries!
