### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by camille-cornet** [qjiangzhao/TEtrimmer#28]
Hi Jiangzhao,

First of all, many thanks for this tool, it is going to be very useful for my project!
I am trying to build a curated TE library for a genus of butterflies. 

The problem is that when running TEtrimmer, the job always stops due to memory usage limits (I gave it up to 1TB, the max I can on my HPC). I have tried with different numbers of threads (48 to 1) and it always crashes. 

The TE library was built using EarlGrey, with a sequential approach (adding more species one by one to get to a representative library).
The final uncurated library is ~11 000 fasta sequences. 
To run TEtrimmer, I built a pangenome to have a representative reference of all my species, and it is 6.8 GB.

What approach do you think I should take to reduce the memory requirements of TEtrimmer? 

Many thanks in advance for your help,

Best,

Camille

**Comment by qjiangzhao** [comment]
Hi Camille, 

No worreis! Thanks you are interested with TEtrimmer. I still remember your introduction about your lovely butterfly project ;)
To be honsest, I have never performed TEtrimmer based on a pan-genome. Theoritically, it is possible. 
You can try to solve this by decreasing the "--max_mas_lines" (default 100) to a smaller number like 50 (the minimum is 15). 
If the problem still exists, you can send me your error message and log file. I will have another look.

Yours sincerely
Jiangzhao

**Comment by camille-cornet** [comment]
Hi Jiangzhao,

Thank you for your swift answer, and sorry for taking so long to respond :) 
I have tried playing with the --max_mas_lines lines setting, even setting it to 15, but the memory issue still persists. 
Although, it runs for more sequences before crashing, so I think it helps a bit.
Do you have another suggestion for me? Or do you think I should reconsider the "pangenome" approach and just select one species to align my TE library to? 

Attached are the log file and the summary.txt file (no error message was generated). 

Best,

Camille

**Comment by camille-cornet** [comment]
Oops, sorry! Here are the files 

[error_file.txt](https://github.com/user-attachments/files/16163689/error_file.txt)
[summary.txt](https://github.com/user-attachments/files/16163690/summary.txt)

And this is the command I used (I have tried with and without  --preset divergent and with various number of threads)

`python TEtrimmer.py --input_file $OUTDIR/Erebia_lib_renamed.fasta --genome_file $PANGENOME --max_msa_lines 15 --top_msa_lines 15 --output_dir $OUTDIR/tetrimmer_output --num_threads 2 --preset divergent`

**Comment by qjiangzhao** [comment]
Based on your "summary.txt" file, the high RAM consumption might due to "BLASTN". 
For example, "rnd_1_family_68" has around 500,000 BLASTN hits. 
You can try to solve this by modifying the TEtrimmer blast() function in file [functions.py](https://github.com/qjiangzhao/TEtrimmer/blob/main/tetrimmer/functions.py) at line 137.
 
BLASTN should have some options to reduce RAM consumption. 

I will also consider this for the next version. Could you give me a feedback if this work?

**Comment by camille-cornet** [comment]
Thanks a lot Jiangzhao!
I will try this now and let you know

**Comment by qjiangzhao** [comment]
No problem. To make it easier, this is the BLASTN command used by TEtrimmer, locates from line 158 to 161:
`       blast_cmd = (f"blastn -task {task} -query {input_file} -db {genome_file} "
                     f"-outfmt \"6 qseqid sseqid pident length mismatch qstart qend sstart send sstrand evalue qcovhsp\" "
                     f"-evalue 1e-40 -qcov_hsp_perc 20 | "
                     f"awk -v ml={min_length} 'BEGIN{{OFS=\"\\t\"}} $4 > ml {{print $0}}' >> {blast_out_file}")`

You can add other BLASTN options behind `-db {genome_file}`

**Comment by camille-cornet** [comment]
Hi Jiangzhao,

Unfortunately after playing with the blastn parameters I still got the memory error. 
I do not have that many blast hits but the run still fails at approximately the same moment, so I do not think that blast was the issue. 
I also tried dividing my TE library into 2 or 3 and it doesn't help. 

Not sure what to do from here, maybe just using less species for the ref pangenome? 

Thanks again,

Camille

**Comment by qjiangzhao** [comment]
To others who might consen:

This RAM issue it due to TE-Aid module, which is integrated into TEtrimmer for visulization. The main reason is the input sequence for TE-Aid is too long and had too many BLAST hits. I will try to fix it for the next version.

**Comment by qjiangzhao** [comment]
Problem fixed.
