### ISSUE TITLE
softmask with TEtrimmer

### ISSUE THREAD

**Issue by enriquepola1996** [qjiangzhao/TEtrimmer#36]
Hello dear Jiangzhao,

First of all, thank you very much for developing this beautiful tool. I'm starting to explore TEtrimmer and was wondering if it's possible to softmask the genome. I saw that there is an option --genome_anno but this returns me a genome hardmask. What I intend to do is perform TE classification, masking, and then annotate my genome. I am working with fungal and plant genomes.

I will greatly appreciate your help.

**Comment by qjiangzhao** [comment]
Hi,

Many thanks you are interested to TEtrimmer. TEtrimmer doesn't support softmask. You can run RepeatMasker with TEtrimmer TE cosnensus library for a softmask annotation. 

Yours sincerely
Jiangzhao

**Comment by enriquepola1996** [comment]
Thank you very much for your valuable comment, I have successfully run TEtrimmer. I have an additional question regarding RepeatMasker, the final goal would be to annotate my genome with BRAKER, so I want to perform a soft masking on my genome but I have a question about the -noint parameter. I'm reading that this parameter only masks low complex/simple repeats (no interspersed repeats), so should I add it or not? I'm thinking about these options:


```
RepeatMasker -lib fungal_T9-families.fa -xsmall -gff -pa 8 fungal_T9_kmer.fasta

RepeatMasker -lib fungal_T9-families.fa -noint  -xsmall  -gff -pa 8 fungal_T9_kmer.fasta
```

I greatly appreciated your help.

**Comment by qjiangzhao** [comment]
If your goal is to annotate genes in your genome. I think you can't use "-noint" option.

**Comment by enriquepola1996** [comment]
Thank you very much for your recommendation, we will be citing TEtrimmer in a couple of articles. You can close this issue.

Greetings.

**Comment by enriquepola1996** [comment]
Thank you very much again, in the commands above I placed fungal_T9-families.fa as input (output of RepeatModeler), but you tell me that I can use TEtrimmer_consensus.fasta (output of TEtrimmer), correct?

Let's say something like this:

```
RepeatMasker -lib TEtrimmer_consensus.fasta -xsmall -gff -pa 8 fungal_T9_kmer.fasta
```

**Comment by enriquepola1996** [comment]
My TEtrimmer output:

```
(TEtrimmer) enrique@DESKTOP-62E8R2K:~/genomas_hongos_2024/transposones_mask/TEtrimmer_T9$ ls -l
total 376
drwxr-xr-x  2    enrique enrique   4096 Jul  8 11:38 Classification_and_deduplication
drwxr-xr-x  2    enrique enrique   208896 Jul  8 11:38 Multiple_sequence_alignment
-rw-r--r--  1     enrique enrique   1543 Jul  8 10:52 Sequence_name_mapping.txt
drwxr-xr-x  2    enrique enrique   4096 Jul  8 10:52 Single_fasta_files
-rw-r--r--  1     enrique enrique    71048 Jul  8 11:38 TEtrimmer_consensus.fasta
-rw-r--r--  1     enrique enrique    72220 Jul  8 11:38 TEtrimmer_consensus_merged.fasta
drwxr-xr-x 10   enrique enrique  4096 Jul  8 10:52 TEtrimmer_for_proof_curation
-rw-r--r--  1     enrique  enrique   3613 Jul  8 11:38 summary.txt
```

**Comment by qjiangzhao** [comment]
You can try this:
`RepeatMasker fungal_T9_kmer.fasta -lib TEtrimmer_consensus_merged.fasta -xsmall -gff -pa 8 -s`

**Comment by enriquepola1996** [comment]
Thank you very much for all the support, it's great that there are developers like you. You can close this issue, again thank you very much.

**Comment by qjiangzhao** [comment]
Thanks ;)
