### ISSUE TITLE
Regarding the intended curation workflow

### ISSUE THREAD

**Issue by acontrerasg** [qjiangzhao/TEtrimmer#39]
Hello,

First of all I wanna  thank you  for developing this tool. The GUI looks very cool and the tools works great. 

However I am a bit confused about  the manual curation procedure workflow proposed by the GUI:

Let's say that I curated a TE from a given Cluster and generate a new consensus (as shown in the video). What is the next step? Shall I curate all the TEs within the cluster?  Shall I re-cluster them each time I update a TE and generate a consensus within a cluster? 

However, the same TE is located both in Annotations_check_required/ and in Clustered_proof_curation/Cluster_XX. Shall I instead curate TEs in Annotation_check_required and in annotation_check_recommend?

If I have gone through all TE consensus found in those two folders (either by generating new consensus or by discarding them) Shall I recreate a new TElib with all TEs in annotation_good, annotation_perfect + only curated TEs (new consensus)  in the other two folders and rerun TE trimmer for clustering?

Thanks a lot!

**Comment by qjiangzhao** [comment]
Hello,

Thanks for your feedback on TEtrimmerGUI. 

All the files in the folder "Clustered_for_proof_curation" are identical to the files from folders "Annotation_perfect", "Annotation_good", "Annotation_check_recommended", and "Annotation_check_required". You can regard TEtrimmer copies all the files to "Clustered_for_proof_curation". 

During the copying process, TEtrimmer groups and places the files (from "Annotation_perfect", "Annotation_good", "Annotation_check_recommended", and "Annotation_check_required") into one "Cluster" when their corresponding TE consensus sequence share more than 90% identity. 

For example, LTRRT_1328 and TE_00000657 are placed into "Cluster2". Their corresponding consensus sequences have 90.65% identify. LTRRT_1328 is originally from  "Annotation_check_recommended" and TE_00000657 is from "Annotation_check_recommended".  Theoretically, you only need to curate and save one TE consensus sequence from each "Cluster". 

When you finish curating all the TEs you can deduplicate them again. By the way, it is also recommended to check the "low copy" and "skipped" TEs by TEtrimmerGUI. 

<img width="898" alt="Screenshot 2024-07-29 at 16 53 21" src="https://github.com/user-attachments/assets/8f85e4c3-4bb8-400e-ba61-7fc272f7115a">

**Comment by acontrerasg** [comment]
Thanks for the answer, 

I get it now, curating a single TE consensus from a cluster can curate the rst of the cluster's consensus by proxy. However, one thing I like about the other folders is that it constructs a priority list of consensi to check "skipped > low_copy > required > recommended > good". 

Is there a way to easily organise clusters like this? I guess I can count the consensus itself within the clusters (I see they have names like reco_check , need_check and so on) folders to prioritise clusters. 

Once I am happy with the new curated consensus, should I run TEtrimmer again? Or just re-mask the genome with the library? What would you recommend?

Thanks a lot!

**Comment by qjiangzhao** [comment]
Currently, TEtrimmerGUI can't provide a priority list. 

You can check the file names in each "Cluster", when "perfect" is detected, you can modify the related folder name to "Perfect_Cluster". When "perfect" isn't detected but "good" is found, you can modify the corresponding folder name to "Good_Cluster". By this way, you can get a priority list. I will consider this for the next version. 

When you finish the proof curation by TEtrimmerGUI, you don't need to run TEtrimmer agian. You can join all curated TE consensue sequence into to TE library, which can be used for the genome-wide TE annotation. 

Yours sincerely
Jiangzhao

**Comment by acontrerasg** [comment]
Many thanks for all the clarifications!
