### ISSUE TITLE
Error during sequence extension on GUI

### ISSUE THREAD

**Issue by Jennifer282** [qjiangzhao/TEtrimmer#44]
Hi, I'm trying to extend a sequence on the TEtrimmer GUI app but I am getting the following error: An error occurred during extension: list index out of range. Refer to terminal for more information. The terminal says the following: 
An error occurred during extension: 
 Traceback (most recent call last):
  File "TEtrimmerGUI.py", line 399, in _extension_function
  File "GUI_functions.py", line 228, in fasta_header_to_bed
IndexError: list index out of range

**Comment by qjiangzhao** [comment]
Hi @Jennifer282, 

Thanks for your question. To use the "Extend" function of TEtrimmerGUI, you must generate your result with TEtrimmer 1.3 or higher version. 

The "fasta" file used for extension should have headers like:

> scaffold_1:343622-349068(+)
> scaffold_1:346171-347467(+)
> scaffold_1:346385-347665(+)
> scaffold_1:346200-347196(+)

If the header of your "fasta" like: 

>1(+)
>2(+)

Please use the new version of TEtrimmer to analysis your consensus sequence. 


Yours sincerely
Jiangzhao
